# Generated by Gemini 3 Pro 
#################################################################################
#                                                                               #
#  HPCC Analyzer - A tool for analyzing HPCC benchmark results                  #
#                                                                               #
#################################################################################

import matplotlib.pyplot as plt
import matplotlib.patheffects as path_effects
import numpy as np
import os
import glob

# ==============================================================================
# 1. CONFIGURATION (HARDCODE YOUR MAX VALUES HERE)
# ==============================================================================

INPUT_FOLDER = "./results"

# These values represent the "1.0" (Outer Edge) of the chart.
# Update these based on your cluster's theoretical theoretical peaks.
# LABELS UPDATED WITH UNITS
REFERENCE_MAX_VALUES = {
    'G-HPL\n(Gflops)': 80.0,
    'G-PTRANS\n(GB/s)': 6.0,
    'RandomRing Latency\n(us)': 0.1,      # Lower is better
    'RandomRing Bandwidth\n(GB/s)': 4.5,
    'S-DGEMM\n(Gflops)': 40.0,
    'S-STREAM\n(GB/s)': 60.0,
    'G-FFT\n(Gflops)': 10.0,
    'G-RandomAccess\n(GUPs)': 0.5
}

# ==============================================================================
# 2. METRIC MAPPING
# ==============================================================================
# Format: 'File_Key': ('Label', Conversion_Func, Is_Lower_Better)
# UPDATED TO MATCH NEW LABELS WITH UNITS

METRIC_MAP = {
    'HPL_Tflops=':                      ('G-HPL\n(Gflops)', lambda x: float(x) * 1000, False),
    'PTRANS_GBs=':                      ('G-PTRANS\n(GB/s)', float, False),
    'RandomlyOrderedRingLatency_usec=': ('RandomRing Latency\n(us)', float, True), 
    'RandomlyOrderedRingBandwidth_GBytes=': ('RandomRing Bandwidth\n(GB/s)', float, False),
    'StarDGEMM_Gflops=':                ('S-DGEMM\n(Gflops)', float, False),
    'StarSTREAM_Triad=':                ('S-STREAM\n(GB/s)', float, False),
    'MPIFFT_Gflops=':                   ('G-FFT\n(Gflops)', float, False),
    'MPIRandomAccess_GUPs=':            ('G-RandomAccess\n(GUPs)', float, False)
}

# ==============================================================================
# 3. HELPERS
# ==============================================================================

def parse_hpcc_file(filepath):
    """Parses a result file and extracts the 8 specific HPCC metrics."""
    data = {}
    for key, (label, _, _) in METRIC_MAP.items():
        data[label] = 0.0

    try:
        with open(filepath, 'r') as f:
            in_summary = False
            for line in f:
                line = line.strip()
                if line == "Begin of Summary section.":
                    in_summary = True
                    continue
                if not in_summary:
                    continue

                for file_key, (label, converter, _) in METRIC_MAP.items():
                    if line.startswith(file_key):
                        try:
                            val_str = line.split('=')[1]
                            data[label] = converter(val_str)
                        except (IndexError, ValueError):
                            pass
                        break
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return None
    return data

def normalize_value(label, actual_value):
    """Normalizes data. Handles 'Lower is Better' for Latency."""
    ref = REFERENCE_MAX_VALUES.get(label, 1.0)
    
    is_latency = False
    for k, v in METRIC_MAP.items():
        if v[0] == label:
            is_latency = v[2]
            break

    if is_latency:
        if actual_value <= 0: return 0.1 
        return ref / actual_value
    else:
        if ref == 0: return 0
        return actual_value / ref

def smart_format(val):
    """Formats numbers based on magnitude to keep chart clean."""
    if val == 0: return "0"
    if val < 0.1: return f"{val:.4f}"
    if val < 1: return f"{val:.3f}"
    if val < 100: return f"{val:.2f}"
    return f"{val:.1f}"

def calculate_dynamic_ylim(labels_to_plot, min_dist):
    """
    Computes the necessary radial limit (padding) based on the 
    stacked text labels to prevent them from being cut off.
    """
    max_y_reached = 1.0 # Default to at least the reference line
    
    # We simulate the stacking logic here
    for angle, items in labels_to_plot.items():
        # Sort by natural normalized value (same logic as plotting)
        sorted_items = sorted(items, key=lambda x: x['norm'])
        
        last_plotted_y = -1.0
        
        for item in sorted_items:
            current_y = item['norm']
            
            # Stacking logic: Push out if too close
            if current_y < last_plotted_y + min_dist:
                current_y = last_plotted_y + min_dist
            
            # Inner limit logic
            if current_y < 0.15:
                current_y = 0.15
                
            last_plotted_y = current_y
        
        # Track the highest Y reached in this angle
        if last_plotted_y > max_y_reached:
            max_y_reached = last_plotted_y
            
    # Add 15% padding on top of the highest label
    return max_y_reached * 1.15

# ==============================================================================
# 4. PLOTTING LOGIC
# ==============================================================================

def create_kiviat_chart(all_data):
    # Setup Data Structure
    labels = list(REFERENCE_MAX_VALUES.keys())
    N = len(labels)
    
    # Angles
    angles = [n / float(N) * 2 * np.pi for n in range(N)]
    angles += angles[:1] # Close loop

    # Setup Plot
    fig, ax = plt.subplots(figsize=(12, 12), subplot_kw=dict(polar=True))
    ax.set_theta_offset(np.pi / 2)
    ax.set_theta_direction(-1)

    # Storage to prevent text overlaps
    labels_to_plot = {} 
    
    colors = plt.cm.get_cmap('tab10', len(all_data))
    
    # ---------------------------------------------------------
    # 1. COLLECT DATA (First Pass)
    # ---------------------------------------------------------
    print(f"\n--- Generating Chart for {len(all_data)} files ---")

    for i, (filename, metrics) in enumerate(all_data.items()):
        values = []
        actual_values_ordered = []
        c = colors(i)
        
        for label in labels:
            val = metrics.get(label, 0.0)
            norm = normalize_value(label, val)
            values.append(norm)
            actual_values_ordered.append(val)
        
        values += values[:1] # Close loop
        
        # Plot Line & Fill
        ax.plot(angles, values, linewidth=2, linestyle='solid', label=filename, color=c)
        ax.fill(angles, values, color=c, alpha=0.1)

        # Store labels for stacking calculation
        for angle, norm_val, act_val in zip(angles[:-1], values[:-1], actual_values_ordered):
            if angle not in labels_to_plot:
                labels_to_plot[angle] = []
            
            labels_to_plot[angle].append({
                'val': act_val,
                'norm': norm_val,
                'color': c
            })

    # ---------------------------------------------------------
    # 2. CALCULATE PADDING & SET LIMITS
    # ---------------------------------------------------------
    MIN_DIST = 0.10 
    
    # Dynamically determine how much space we need
    dynamic_limit = calculate_dynamic_ylim(labels_to_plot, MIN_DIST)
    
    # Apply Limits
    ax.set_ylim(0, dynamic_limit)
    
    # Draw Axes Labels
    plt.xticks(angles[:-1], labels, size=10, weight='bold')
    ax.set_rlabel_position(0)
    plt.yticks([0.5, 1.0], ["50%", "Ref"], color="grey", size=8)

    # ---------------------------------------------------------
    # 3. PLOT TEXT (Second Pass - With Stacking)
    # ---------------------------------------------------------

    for angle, items in labels_to_plot.items():
        # Sort items by normalized position (from center to outside)
        items.sort(key=lambda x: x['norm'])
        
        last_plotted_y = -1.0 # Initialize far below zero
        
        for item in items:
            # Check for collision
            current_y = item['norm']
            
            # If too close to previous, push it out
            if current_y < last_plotted_y + MIN_DIST:
                current_y = last_plotted_y + MIN_DIST
            
            # Hard limit: Don't put label exactly at center
            if current_y < 0.15:
                current_y = 0.15

            last_plotted_y = current_y
            
            # Format and Plot
            txt_label = smart_format(item['val'])
            txt = ax.text(angle, current_y, txt_label, 
                          ha='center', va='center', 
                          fontsize=9, fontweight='bold', color=item['color'])
            
            # Add White Outline (Halo)
            txt.set_path_effects([
                path_effects.Stroke(linewidth=3, foreground='white'),
                path_effects.Normal()
            ])

    # ---------------------------------------------------------
    # FINAL TOUCHES
    # ---------------------------------------------------------
    
    # Reference Line (Red Dashed)
    ref_values = [1.0] * (N + 1)
    ax.plot(angles, ref_values, linewidth=1, linestyle='--', color='red', label='Reference Max')

    plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1.1))
    plt.title("HPC Challenge Benchmark Results", size=18, y=1.08, weight='bold')
    
    outfile = "hpcc_kiviat_results.png"
    plt.tight_layout()
    plt.savefig(outfile, dpi=300)
    print(f"\nSaved chart to: {outfile}")
    plt.show()

# ==============================================================================
# 5. MAIN
# ==============================================================================

if __name__ == "__main__":
    if not os.path.exists(INPUT_FOLDER):
        os.makedirs(INPUT_FOLDER)
        print(f"Created '{INPUT_FOLDER}'. Please add .txt files.")
        exit()

    files = glob.glob(os.path.join(INPUT_FOLDER, "*.txt"))
    if not files:
        print(f"No .txt files found in {INPUT_FOLDER}")
        exit()

    aggregated_data = {}
    for f in files:
        fname = os.path.splitext(os.path.basename(f))[0]
        parsed = parse_hpcc_file(f)
        if parsed:
            aggregated_data[fname] = parsed

    if aggregated_data:
        create_kiviat_chart(aggregated_data)
    else:
        print("No valid data found.")